### ISSUE TITLE
node: HTTPS urls use HTTP instead

### ISSUE THREAD

**Issue by jlai** [jakutis/httpinvoke#13]
The node version of httpinvoke ignores "https" in URLs and connects to plain http instead.

For example,

```js
var httpinvoke = require('httpinvoke');

httpinvoke('https://www.eff.org', 'GET', function (err, body, status, headers) {
  console.log(status + ': ' + JSON.stringify(headers) + '\n\n' + body);
});
```

returns a redirect to the https url instead of the correct https content.

The code in src/node.js needs to be modified to do something like

```js
var httpOrHttps = uri.protocol === 'https:' ? https : http; // uri.protocol is always lowercase
var req = httpOrHttps.request({
```

**Comment by jakutis** [comment]
Fixed. Thank you very much! This was a huge mistake..

**Comment by jlai** [comment]
Thanks for fixing! :+1:
