### ISSUE TITLE
How to add `mozSystem` to XHR object?

### ISSUE THREAD

**Issue by novabyte** [jakutis/httpinvoke#14]
Mozilla has two custom extensions which can be added to the `XMLHttpRequest` object: `mozSystem` and `mozAnon`.

`mozSystem` is particularly useful because it disables the Same Origin Policy on Firefox OS applications. This allows FFxOS mobile devices to avoid preflight `OPTIONS` requests. The full documentation on this property states:

> Setting this flag to true allows making cross-site connections without requiring the server to opt-in using CORS.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest

Is there a way to add `mozSystem: true` to the underlying `XMLHttpRequest` object built up by `httpinvoke`?

**Comment by jakutis** [comment]
Hello, the functionality you want is now implemented in the just released version 1.4.0 with commits f72dff97f2e94909f7a3f52b9bb030a03241eaf0 and 4347b69da95b3635593a755b4176ba26fbdd5bc7. To do what you want, just add an option "system":

```javascript
httpinvoke("http://example.org/", {system:true}).then(...);
```

Beware that I have not tested if it actually works. Please tell me how it goes on your devices, or give me a hint for me how can I test by myself - do I really have to create a privileged and reviewed app in Firefox Marketplace? Will it work on emulator?

**Comment by novabyte** [comment]
@jakutis I can test this in the emulator and on a Firefox OS device. Thanks for the very prompt work; it's late for me now but I'll test it in the morning. :smile:

**Comment by novabyte** [comment]
@jakutis Thanks I've tested it and it all works! :sunglasses:
