### ISSUE TITLE
Why is User-Agent header forbidden in node ?

### ISSUE THREAD

**Issue by moul** [jakutis/httpinvoke#15]
I think the two next lines are not needed when using the node.js version of this library.
This protection seems only related to XmlHTTPRequest calls and not from those performed using https://nodejs.org/api/http.html

https://github.com/jakutis/httpinvoke/blob/fcbd018f926e03be96585ffe95d708f8c735172f/httpinvoke-node.js#L124-L125

**Comment by jakutis** [comment]
Hi, thanks for the correct suggestion. I implemented the fix in the just released version 1.4.0 with commit d216880937f42b9024d1e6b3b594182f0465d746.

Does it work for you now?

**Comment by moul** [comment]
Yes it does :ok_hand: 

Thanks a lot
